# Site settings
title: Mateusz Åoskot
email: mateusz@loskot.net
description: > # this means to ignore newlines until "baseurl:"
   "My personal website on hacking on, working out and living up"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mloskot.github.io" # the base hostname & protocol for your site
twitter_username: mloskot
github_username:  mloskot

# Build settings
markdown: kramdown
