# Site settings
title: "Mateusz Åoskot :: hacking on, working out, living up"
email: mateusz@loskot.net
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mloskot.github.io" # the base hostname & protocol for your site
twitter_username: mloskot
github_username:  mloskot

# Build settings
markdown: kramdown
